### ISSUE TITLE
Support StaticBlock inside a streamfield

### ISSUE THREAD

**Issue by mikemonteith** [wagtail/wagtail-factories#14]
It seems that the StreamFieldFactory assumes that all blocks will have fields. However a StaticBlock has no fields.

I propose setting the value to `True` inside a streamfield definition should create the block with no parameters. This could also work for StructBlocks where the field values are already defined in the relevant StructBlockFactory.
```
    page = MyTestPageWithStreamFieldFactory(
        parent=root_page,
        body__0__char_array__0='foo',
        body__0__char_array__1='bar',
        body__2__int_array__0=100,
        body__1__struct__title='My Title',
        body__1__struct__item__value=100,
        body__1__struct__image__image=None,
        body__3__image__image__title='Blub',
        body__4__static_block=True,
    )
```

**Comment by jams2** [comment]
Hi @mikemonteith , I believe this functionality is already covered, but poorly documented. The syntax to generate the default value for a member in a `StreamValue` is, taking your above example:

```python
MyTestPageWithStreamFieldFactory(
    parent=root_page,
    body__0="static_block",
)
```

(`<stream_field_name>__<index>="<block_name>"`)
