### ISSUE TITLE
Not compatable with Factory Boy 3.0

### ISSUE THREAD

**Issue by hammygoonan** [wagtail/wagtail-factories#28]
Factory Boy 3.0 was released earlier today with a [breaking change](https://factoryboy.readthedocs.io/en/3.0.0/changelog.html#breaking-changes) to imports.

I'm now getting this error: `AttributeError: module 'factory' has no attribute 'DjangoModelFactory`

here's the full stack trace:

```
/blocks/tests/media_block_tests.py:8: in <module>
    import wagtail_factories
/usr/local/lib/python3.8/site-packages/wagtail_factories/__init__.py:1: in <module>
    from .blocks import *
/usr/local/lib/python3.8/site-packages/wagtail_factories/blocks.py:8: in <module>
    from wagtail_factories.factories import ImageFactory
/usr/local/lib/python3.8/site-packages/wagtail_factories/factories.py:42: in <module>
    class MP_NodeFactory(factory.DjangoModelFactory):
E   AttributeError: module 'factory' has no attribute 'DjangoModelFactory'
```

**Comment by hammygoonan** [comment]
Just submitted a [PR](https://github.com/mvantellingen/wagtail-factories/pull/29) to fix this

**Comment by marteinn** [comment]
PR is merged so I'm closing this. Thanks for the excellent work @hammygoonan!

**Comment by hammygoonan** [comment]
Happy to help @marteinn !
