### ISSUE TITLE
StreamFieldFactory not working

### ISSUE THREAD

**Issue by confuzeus** [wagtail/wagtail-factories#31]
`    images = wagtail_factories.StreamFieldFactory(
        {"image": wagtail_factories.ImageChooserBlockFactory},
    )`

The images attribute is an empty list after I run this factory. What am I doing wrong?

**Comment by felicemcc** [comment]
I have the same case... On the model, the body field is a textfield. And a, example code would be:

`class ArticlePageFactory(wagtail_factories.PageFactory):
    title = factory.Faker('sentence', nb_words=4)
    body = wagtail_factories.StreamFieldFactory({
        'paragraph':  RichTextBlockFactory,
        'heading': wagtail_factories.blocks.CharBlockFactory,
    })
    live = True
`

Then on the tests:

`article = ArticlePageFactory(parent=root)`

I get for article.body
`<StreamValue []>`

**Comment by joshuadavidthomas** [comment]
+1 for me as well.

On a fresh project on a cloud instance of Gitpod, after running `wagtail start mysite` and `pip install wagtail-factories`:

```python
# home/models.py
from django.db import models

from wagtail.core.models import Page
from wagtail.core import blocks
from wagtail.core.fields import StreamField
from wagtail.admin.edit_handlers import StreamFieldPanel


class HomePage(Page):
    body = StreamField([
        ('heading', blocks.CharBlock(form_classname="full title")),
    ])
    
    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]
```

```py
# home/factories.py
import wagtail_factories

from .models import HomePage

class HomePageFactory(wagtail_factories.PageFactory):
    title = "test page"
    body = wagtail_factories.StreamFieldFactory({
        "heading": "test heading"
    })

    class Meta:
        model = HomePage
```

```shell
gitpod /workspace/wagtail-gitpod $ python manage.py shell
Python 3.8.12 (default, Sep 13 2021, 03:12:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from home.factories import HomePageFactory

In [2]: home = HomePageFactory()

In [3]: home.title
Out[3]: 'test page'

In [4]: home.body
Out[4]: <StreamValue []>
```

---

I would love to help out and fix this issue, but I'm at a loss as to where to start debugging this issue. Any tips?

**Comment by joshuadavidthomas** [comment]
@confuzeus I don't believe this issue should be closed as it does seem like a genuine bug.
