### ISSUE TITLE
Future maintenance? 

### ISSUE THREAD

**Issue by easherma** [wagtail/wagtail-factories#32]
@mvantellingen there have been some PRs open on this project for awhile, as well as changes pushed to master but not tagged in a release.

Would you be interested in more collaboration on this project? I think there are ways the community could build on and flesh out its functionality, despite it not being a super active project.

**Comment by mvantellingen** [comment]
Hi @easherma as discussed via e-mail this repository is now moved to wagtail to allow more people to contribute to it 👍
