### ISSUE TITLE
Drop support for Wagtail 2.7 and 2.10

### ISSUE THREAD

**Issue by marteinn** [wagtail/wagtail-factories#43]
We currently support Wagtail 2.7 and 2.10, this support should be dropped as both versions has reached EOL. We should instead support 2.11 and 2.13 (as by https://github.com/wagtail/wagtail/wiki/Release-schedule).

Changes needs to be done in the CI, setup.py install requires and tox.ini.

**Comment by Stormheg** [comment]
In the process of doing something similar for wagtail-bakery: https://github.com/wagtail/wagtail-bakery/pull/62

I'll assign this to myself and do this in the next week or so.

**Comment by marteinn** [comment]
👋 Hi @Stormheg! Woops, I missed your comment and already pushed these changes with these two commits:
- https://github.com/wagtail/wagtail-factories/commit/85adabc8743d665f2a012dcd18650fc86f78973a
- https://github.com/wagtail/wagtail-factories/commit/4b315fe4aa9df75fe0288e7f402557cc3a2736eb

But if you got the time, feedback is much appreciated! :)

**Comment by Stormheg** [comment]
@marteinn well done! 👏

In that case I'll unassign myself😁

**Comment by marteinn** [comment]
@Stormheg Awesome, in that case I'm closing this issue :)
