### ISSUE TITLE
bump for wagtail 2.14.1? 

### ISSUE THREAD

**Issue by Pomax** [wagtail/wagtail-factories#48]
Looking at the tox.ini ti seems that the latest version of wagtail that's supported is 2.13, could 2.14 support be added?

**Comment by marteinn** [comment]
Hi @Pomax! The code in the master branch already supports Wagtail 2.14, but is not included in the CI suite. I just opened a PR to include this. https://github.com/wagtail/wagtail-factories/pull/49
