### ISSUE TITLE
Is help needed?

### ISSUE THREAD

**Issue by jeromelebleu** [wagtail/wagtail-factories#51]
I am wondering who is still active in the contributors and have time to maintain this project. I think at least tests should be updated to ensure last Wagtail and Django versions are still supported. Feel free to ask if any help is needed.

**Comment by thibaudcolas** [comment]
Hi @jeromelebleu, thank you for offering to help. We’re checking who we currently have available to maintain this package, and how many people would ideally be needed – I’ll get back to you once we know more.

**Comment by thibaudcolas** [comment]
@jeromelebleu are you still interested in helping with maintenance? If so would be nice for you to come say hi on our [Slack workspace](https://github.com/wagtail/wagtail/wiki/Slack), where we now have a channel for this package.
