### ISSUE TITLE
Wagtail 5.0 not supported

### ISSUE THREAD

**Issue by rikva** [wagtail/wagtail-factories#73]
When attempting to upgrade to Wagtail 5.0:

```wagtail-factories 4.0.0 depends on wagtail<5.0 and >=2.15```

**Comment by zerolab** [comment]
Wagtail 5.0 incorporates wagtail-factories in `wagtail.test.utils` see https://github.com/wagtail/wagtail/tree/stable/5.0.x/wagtail/test/utils/wagtail_factories

**Comment by rikva** [comment]
Thanks for your reply. Totally missed that. So the projects have basically merged?

**Comment by zerolab** [comment]
We had an internal conversation and it makes sense to make a new release for wagtail-factories that removes the upper bound for Wagtail.

Wagtail copied wagtail-factories to core to avoid cyclic dependencies, but we haven't yet decided on whether we make the whole bit official, or treat that as an internal dependency and leave wagtail-factories evolve at its own pace

**Comment by jams2** [comment]
Released in https://github.com/wagtail/wagtail-factories/releases/tag/v4.1.0
